### PR TITLE
Directly use MagicBus to manage Kolibri's state 

### PR DESCRIPTION
**Pull request by dylanmccall**
With Kolibri 0.15, KolibriProcessBus provides a state machine to manage
starting and stopping Kolibri. With this new functionality, we can
remove most of the existing code in kolibri-daemon for stopping and
starting Kolibri, and instead populate KolibriServiceContext by using
MagicBus plugins. Instead of using LauncherProcess to communicate with a
a collection of Kolibri-related processes, KolibriServiceManager can use
a similar interface to communicate with a single DjangoProcess.

https://phabricator.endlessm.com/T32972

### CODE REVIEW

**Comment by ramcq** [comment]
I think we have images out in the wild which rely on content extensions - https://github.com/endlessm/endless-image-config/search?q=org.learningequality.Kolibri.Content - won't this make a bunch of content disappear when they OTA update the Kolibri app?

**Comment by dylanmccall** [comment]
@ramcq oh yeah, that _wasn't_ a dream. Okay, I'll need to put it back, but I think it can be a bit less complicated now at least :) I'll make a Phabricator ticket to track deprecating the things.

**Review by danigm — APPROVED** [review]
Looks good to me. Maybe it's good idea to squash the commits about removing and adding back the content extension support, but there are a lot of commits in between and if it's too complex to merge the first and last commit, it's okay for me to do that.

**Comment by dylanmccall** [comment]
Thanks for taking a look! I rebased this to organize the various redundant changes into some more organized commits.

**Pull request merged**
